apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: jesseqin/my-fastapi-app
    argocd-image-updater.argoproj.io/jesseqin_my-fastapi-app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: jesseqin/my-fastapi-app:latest
          ports:
            - containerPort: 8000